# Generated by Django 2.0 on 2017-12-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20171224_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengunjung',
            fields=[
                ('pengunjung_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField()),
                ('film', models.ManyToManyField(to='movie.Film')),
                ('pengunjung', models.ManyToManyField(to='movie.Pengunjung')),
            ],
        ),
    ]
