# Generated by Django 2.0 on 2017-12-28 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_pengunjung_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='film',
        ),
        migrations.AddField(
            model_name='rating',
            name='film',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movie.Film'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='rating',
            name='pengunjung',
        ),
        migrations.AddField(
            model_name='rating',
            name='pengunjung',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movie.Pengunjung'),
            preserve_default=False,
        ),
    ]
