# Generated by Django 2.0 on 2018-01-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20171228_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='gmr',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='ket',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
